### PR TITLE
Updated CSS

### PR DESCRIPTION
**Pull request by JettBurns14**
Mainly changed CSS, and adjusted the layout.

### CODE REVIEW

**Comment by xymostech** [comment]
Can you post a screenshot of what this looks like?

**Comment by JettBurns14** [comment]
image

**Comment by xymostech** [comment]
Cool! This looks awesome! Could you post a screenshot of the entire page? You can do that in the device emulator: https://developers.google.com/web/updates/2017/04/devtools-release-notes#screenshots

It looks like the events on the first and last days aren't being sized correctly, and the spaces between the runs are gone. Also, could you mock out the "current time" to show what the current time marker looks like?

**Comment by JettBurns14** [comment]
Yeah, that spacing for the first and last events (and all other events) was removed, so they are all spaced apart by the same amount (2px). This screenshot shows the "current time" marker and a popup.
my-gdq-screenshot

**Comment by xymostech** [comment]
Hmm, I'd be okay getting rid of the set-up spacing between events, but we'll have to make sure that the current time marker shows up in the right place. The way I did it originally (ab)using flex needs those spaces to be there to work correctly. Also, you should add back the spacing before the pre-show and after the last game, because as-is it looks like the pre-show starts at midnight, and the events on the first day look way longer than they are!

**Comment by JettBurns14** [comment]
Ok, added back the spacing before the pre-show and after the last game (and all other events). All other style is the same. Looks like the current time indicator shows up in the right place again. 
Since this PR is more about style, I won't mess with that specific spacing or flex proportionality, it's sensitive! Look good?
gdq-screenshot

**Comment by xymostech** [comment]
LGTM! I'm going to merge this so I can publish it, but I'd love to see some of the features of your original design come back if you'd like to make another PR. The style of your popover looked really good, and the format of the text in the boxes (with the start-end times and bolded name) also looked awesome! Is there a reason you undid those?

**Comment by xymostech** [comment]
New styles published! https://gdq-schedule.com/

**Comment by JettBurns14** [comment]
Ah, I left out the start-end times and bolded names mainly because some events aren't tall enough to fit both. Screenshot shows what it would look like with them.

The current popover doesn't have the Duration by itself, it can be added back if that looks better. Is that what's missing?
gdq-screenshot

**Pull request merged**
